version: "3.9"

services:
  nginx:
    build: "../dx-construction/.docker/nginx"
    container_name: dx-construction-nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: "../dx-construction/.docker/php"
    container_name: dx-construction-app
    working_dir: /app
    volumes:
      - ".:/app"
      - "./.docker/php/php.ini:/user/local/etc/php/conf/d/php.ini"
    ports:
      - "9000:9000"
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: dx-construction-mysql
    build: "../dx-construction/.docker/mysql"
    ports:
      - "3306:3306"
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: dx-construction
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:6.2-buster
    container_name: dx-construction-redis
    ports:
      - "6379:6379"






